// test/turn.test.js — turn division, the user-text cleaning projection, and the Turn Record primitives.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  activePathOrdinals, buildSearchTerms, buildSkeleton, cleanAskAnswer, cleanUserText, groupTurns,
  parseNoteSections, projectTurnRecord, renderNoteSections, slotKeysOf, snapshotDigest, storedUText,
  truncateToTokens, U_TEXT_TOKENS,
} from '../lib/turn.js';
import { DEFAULT_CTP } from '../lib/constants.js';
import { charsToTokens } from '../lib/measure.js';
import { enumerateLines, readCanonicalTranscript } from '../lib/dialogue-fold.js';
import {
  userMessage, assistantObservation, assistantToolUse, toolResult, writeTranscript, ts,
} from './helpers/transcript-fixtures.js';

const dir = mkdtempSync(join(tmpdir(), 'sw-turn-'));

// 所有 lines 都由合成 transcript 过 enumerateLines 得到 —— 不碰真实语料，不内嵌真实标识符
const linesOf = (entries) => enumerateLines(readCanonicalTranscript(writeTranscript(dir, entries)));
const lines = linesOf([
  userMessage({ uuid: 'u1', text: '第一个问题', timestamp: ts(1) }),
  assistantObservation({ uuid: 'a1', parentUuid: 'u1', messageId: 'm1', timestamp: ts(2),
    blocks: [{ type: 'text', text: '回答' }] }),
  userMessage({ uuid: 'i1', parentUuid: 'a1', text: '[Request interrupted by user]', timestamp: ts(3) }),
  assistantObservation({ uuid: 'a2', parentUuid: 'i1', messageId: 'm2', timestamp: ts(4),
    blocks: [{ type: 'text', text: '续答' }] }),
  userMessage({ uuid: 'u2', parentUuid: 'a2', text: '第二个问题', timestamp: ts(5) }),
]);
const clearOnlyLines = linesOf([
  userMessage({ uuid: 'c1', text: '<command-name>/clear</command-name>', timestamp: ts(1) }),
]);
// 第一个 head U 之前就有行：转录首条是 assistant（parentUuid 省略 ⇒ 它自己是 root）。
// 真实来源是 afterLatestCompact 在 compact summary 之后切一刀、切完首条不是 user 行。
const preHeadLines = linesOf([
  assistantObservation({ uuid: 'a0', messageId: 'm0', timestamp: ts(1),
    blocks: [{ type: 'text', text: '第一个 head U 之前的行' }] }),
  userMessage({ uuid: 'u1', parentUuid: 'a0', text: '第一个问题', timestamp: ts(2) }),
  assistantObservation({ uuid: 'a1', parentUuid: 'u1', messageId: 'm1', timestamp: ts(3),
    blocks: [{ type: 'text', text: '回答' }] }),
]);

// `/exit` 的真实三件套（caveat / 命令回显 / stdout）写进 CC 即将丢弃的那个文件，进程退出；之后
// `claude -c` resume 回同一个文件时，CC 补一条 assistant「No response requested.」parent 到 stdout
// 行上 —— 于是它落进 `/exit` 这个 turn。物理行依次是：头 U、assistant、caveat（吸收进头 U 那个
// turn）、`/exit` 回显、stdout（吸收）、那条 assistant、resume 后的头 U、assistant。
const exitEchoLines = linesOf([
  userMessage({ uuid: 'xe-u1', text: 'deploy 完了，重启一下', timestamp: ts(1) }),
  assistantObservation({ uuid: 'xe-a1', parentUuid: 'xe-u1', messageId: 'xe-m1', timestamp: ts(2),
    blocks: [{ type: 'text', text: 'deployed' }] }),
  userMessage({ uuid: 'xe-cav', parentUuid: 'xe-a1', timestamp: ts(3),
    text: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>' }),
  userMessage({ uuid: 'xe-cmd', parentUuid: 'xe-cav', timestamp: ts(4),
    text: '<command-name>/exit</command-name>\n            <command-message>exit</command-message>\n            <command-args></command-args>' }),
  userMessage({ uuid: 'xe-out', parentUuid: 'xe-cmd', timestamp: ts(5),
    text: '<local-command-stdout>Catch you later!</local-command-stdout>' }),
  assistantObservation({ uuid: 'xe-a2', parentUuid: 'xe-out', messageId: 'xe-m2', timestamp: ts(6),
    blocks: [{ type: 'text', text: 'No response requested.' }] }),
  userMessage({ uuid: 'xe-u2', parentUuid: 'xe-a2', text: 'resume 之后接着干', timestamp: ts(7) }),
  assistantObservation({ uuid: 'xe-a3', parentUuid: 'xe-u2', messageId: 'xe-m3', timestamp: ts(8),
    blocks: [{ type: 'text', text: 'ok' }] }),
]);

test('正文含 <command-name> 的人类消息判为 HEAD 且保住全文', () => {
  const raw = '我们要不要把 <command-name>/clear</command-name> 也算成 head U？';
  const r = cleanUserText(raw);
  assert.equal(r.kind, 'HEAD');
  assert.ok(r.cleaned.includes('我们要不要把'));
  assert.ok(r.cleaned.includes('也算成 head U？'));
});

test('裸命令：包装剥净，投影只剩命令名', () => {
  assert.deepEqual(cleanUserText('<command-name>/clear</command-name>'), { kind: 'HEAD', cleaned: '/clear' });
});

test('命令 + args 按 `name args` 连接', () => {
  const r = cleanUserText('<command-name>/model</command-name><command-args>opus</command-args>');
  assert.equal(r.cleaned, '/model opus');
});

test('多个 command-name 全部按序保留，无胜出规则', () => {
  const r = cleanUserText('<command-name>/a</command-name><command-name>/b</command-name>');
  assert.equal(r.cleaned, '/a — /b');
});

test('ABSORB 三类', () => {
  assert.equal(cleanUserText('[Request interrupted by user]').kind, 'ABSORB');
  assert.equal(cleanUserText('<local-command-stdout>ok</local-command-stdout>').kind, 'ABSORB');
  assert.equal(cleanUserText('<system-reminder>x</system-reminder>').kind, 'ABSORB');
});

test('ABSORB 判据基于 residue 是否为空，不基于是否含标签', () => {
  const r = cleanUserText('看 <local-command-stdout>ok</local-command-stdout> 这段输出说明什么');
  assert.equal(r.kind, 'HEAD');
  assert.ok(r.cleaned.includes('这段输出说明什么'));
});

test('裸 Caveat: 行是正文，不剥不吞', () => {
  const r = cleanUserText('第一行\nCaveat: 注意这个\n第三行');
  assert.equal(r.kind, 'HEAD');
  assert.ok(r.cleaned.includes('Caveat: 注意这个'));
  assert.equal(cleanUserText('Caveat: 别用 rm -rf').kind, 'HEAD');
});

test('投影为空即 ABSORB：空命令名与孤立 args 都不开出空 u_text 的 turn', () => {
  assert.deepEqual(cleanUserText('<command-name></command-name>'), { kind: 'ABSORB', cleaned: '' });
  assert.deepEqual(cleanUserText('<command-args>opus</command-args>'), { kind: 'ABSORB', cleaned: '' });
});

test('groupTurns: ABSORB 留在 span 内、不开 turn；第一个 head U 之后每行恰好落一个 span', () => {
  const turns = groupTurns(lines); // fixture: U, A, [Request interrupted], A, U
  assert.equal(turns.length, 2);
  assert.equal(turns[0].lines.length, 4);
  assert.equal(turns.reduce((n, t) => n + t.lines.length, 0), lines.length);
});

test('groupTurns: T 是头 U 的 lineOrdinal，原样取用', () => {
  assert.equal(groupTurns(lines)[0].t, lines[0].t);
});

test('groupTurns: 第一个 head U 之前的行不落任何 span —— 不为它造 anchor', () => {
  assert.equal(preHeadLines.length, 3);
  const turns = groupTurns(preHeadLines);
  assert.equal(turns.length, 1);
  assert.equal(turns[0].t, preHeadLines[1].t);
  // 行数之和严格小于总行数：第一个 head 之后每行恰好落在一个 span，之前的行不落任何 span
  assert.equal(turns.reduce((n, t) => n + t.lines.length, 0), preHeadLines.length - 1);
  assert.ok(!turns.some(t => t.lines.some(l => l.anchor === 'a0')),
    '被丢的行不得出现在任何 span 里');
  assert.ok(!turns.some(t => t.anchorUuid === 'a0'), '被丢的行不得成为任何 turn 的持久化 anchor');
});

test('groupTurns: 真 note-less 由 hasAssistantActivity=false 标记（无可见 A 且无工具）', () => {
  const turns = groupTurns(clearOnlyLines);
  assert.equal(turns[0].hasAssistantActivity, false);
});

// resume 补的那条 assistant 属于 harness 对自己本地命令的确认，不是这个 turn 的 assistant 贡献。
// 行照旧落在 span 里（骨架仍要看得见它），只是门不开。
test('groupTurns: `/exit` 回显 turn 不算有 assistant 活动，但行一条不丢', () => {
  const turns = groupTurns(exitEchoLines);
  assert.deepEqual(turns.map(t => t.cleanedU), ['deploy 完了，重启一下', '/exit', 'resume 之后接着干']);
  assert.deepEqual(turns.map(t => t.hasAssistantActivity), [true, false, true]);
  assert.deepEqual(turns[1].lines.map(l => l.anchor), ['xe-cmd', 'xe-out', 'xe-a2']);
  assert.equal(turns.reduce((n, t) => n + t.lines.length, 0), exitEchoLines.length);
});

// 判据要认 harness 的那次回显，两个合取子各挡一侧的人类消息：引用了 tag 的散文（投影有残留正文），
// 和正文字面就是 `/exit` 的消息（没有 tag）。两条都必须照旧拿槽。
test('groupTurns: 引用 `<command-name>/exit</command-name>` 的人类散文照旧拿槽', () => {
  const prose = linesOf([
    userMessage({ uuid: 'xp-u', timestamp: ts(1),
      text: '要不要把 <command-name>/exit</command-name> 也算成无槽的？' }),
    assistantObservation({ uuid: 'xp-a', parentUuid: 'xp-u', messageId: 'xp-m', timestamp: ts(2),
      blocks: [{ type: 'text', text: '要' }] }),
  ]);
  assert.equal(groupTurns(prose)[0].hasAssistantActivity, true);
});

// 一个降级到信封原文的 ask head 的投影可以是任意文本，包括这一条。它是被裁定的用户意图，槽照旧要
// 给；而它是工具行，根本没有 message 可读 —— 所以 kind 判据必须在解引用之前。
test('groupTurns: 投影恰好是 `/exit` 的 ask head 照旧拿槽，且不因无 message 而抛错', () => {
  const askHead = linesOf([
    userMessage({ uuid: 'xa-u', text: '开始', timestamp: ts(1) }),
    assistantToolUse({ uuid: 'xa-ask', parentUuid: 'xa-u', messageId: 'xa-m', toolUseId: 'xa-tu',
      name: 'AskUserQuestion', input: { questions: [] }, timestamp: ts(2) }),
    toolResult({ uuid: 'xa-ans', parentUuid: 'xa-ask', toolUseId: 'xa-tu', content: '/exit',
      timestamp: ts(3) }),
    assistantObservation({ uuid: 'xa-a', parentUuid: 'xa-ans', messageId: 'xa-m2', timestamp: ts(4),
      blocks: [{ type: 'text', text: '照办' }] }),
  ]);
  const turn = groupTurns(askHead).find(t => t.cleanedU === '/exit');
  assert.equal(turn.lines[0].message, null, '前提：ask head 是工具行，没有 message');
  assert.equal(turn.hasAssistantActivity, true);
});

test('groupTurns: 正文字面就是 `/exit` 但没有命令 tag 的人类消息照旧拿槽', () => {
  const bare = linesOf([
    userMessage({ uuid: 'xb-u', text: '/exit', timestamp: ts(1) }),
    assistantObservation({ uuid: 'xb-a', parentUuid: 'xb-u', messageId: 'xb-m', timestamp: ts(2),
      blocks: [{ type: 'text', text: '好' }] }),
  ]);
  const [turn] = groupTurns(bare);
  assert.equal(turn.cleanedU, '/exit', '投影确实撞上了命令名 —— 这才是这条用例的前提');
  assert.equal(turn.hasAssistantActivity, true);
});

test('T 就是 grep -n 的行号：解析失败的行同样吃掉一个号', () => {
  const p = join(dir, 'malformed.jsonl');
  writeFileSync(p, '{not json\n' + JSON.stringify(userMessage({ uuid: 'u1', text: 'hi', timestamp: ts(1) })) + '\n');
  const folds = readCanonicalTranscript(p).folds;
  assert.equal(folds[0].sourceRef.lineOrdinal, 2);   // 坏行吃掉的是它自己那个号
  const clean = writeTranscript(dir, [userMessage({ uuid: 'u1', text: 'hi', timestamp: ts(1) })]);
  assert.equal(readCanonicalTranscript(clean).folds[0].sourceRef.lineOrdinal, 1);
});

test('truncateToTokens 是 charsToTokens 的精确反解', () => {
  const cut = truncateToTokens('中'.repeat(500), U_TEXT_TOKENS, DEFAULT_CTP);
  assert.ok(charsToTokens(cut, DEFAULT_CTP) <= U_TEXT_TOKENS);
  assert.ok(charsToTokens(cut + '中', DEFAULT_CTP) > U_TEXT_TOKENS);
});

test('truncateToTokens: 切点落在代理对中间时退到完整对，不留半个字符', () => {
  // 'x' 把星体字符推到奇数偏移：limit 4 的原始切点是 12，正好落在第 6 对的高位代理上。
  const cut = truncateToTokens('x' + '😀'.repeat(50), 4, DEFAULT_CTP);
  const last = cut.charCodeAt(cut.length - 1);
  assert.ok(last < 0xD800 || last > 0xDBFF, '不得以孤立高位代理结尾');
  assert.equal(cut, 'x' + '😀'.repeat(5));
  assert.ok(charsToTokens(cut, DEFAULT_CTP) <= 4);
});

test('storedUText: 截断状态由 u_original_chars > u_text.length 派生', () => {
  const { uText, uOriginalChars } = storedUText('中'.repeat(500));
  assert.equal(uOriginalChars, 500);
  assert.ok(uOriginalChars > uText.length);
});

test('projectTurnRecord: NULL note ⇒ 键不出现；截断态由字符数之差派生', () => {
  const row = { anchorUuid: 'u1', uText: 'abc', uOriginalChars: 12, note: null };
  const out = projectTurnRecord(row, new Map([['u1', 7]]));
  assert.deepEqual(out, { t: 7, u: 'abc [truncated; 12 chars]' });
  assert.equal('note' in out, false);
});

// t 为 null 只代表「没有可读转录可定位」，即 `CONTEXT.md` Unverified Turn Record 的空 T 地址。anchor
// 不在一张非空 map 里是废弃 turn，由调用方排除 —— 所以这里只测无 map 与空 map 两种缺失形态。
test('projectTurnRecord: 转录缺失（无 ordinals / 空 map）⇒ t 为 null，note 原样带出', () => {
  const row = { anchorUuid: 'u1', uText: 'abc', uOriginalChars: 3, note: '记录' };
  assert.deepEqual(projectTurnRecord(row, null), { t: null, u: 'abc', note: '记录' });
  assert.equal(projectTurnRecord(row, new Map()).t, null);
});

test('projectTurnRecord: 缺失由 map 里有没有这个 anchor 决定，不由 t 的真假值决定', () => {
  const row = { anchorUuid: 'u1', uText: 'abc', uOriginalChars: 3, note: null };
  assert.equal(projectTurnRecord(row, new Map([['u1', 0]])).t, 0);
});

test('activePathOrdinals: turn 头的 anchor uuid → 该 turn 的 T；非头行不可查', () => {
  const ordinals = activePathOrdinals(readCanonicalTranscript(writeTranscript(dir, [
    userMessage({ uuid: 'u1', text: '问', timestamp: ts(1) }),
    assistantObservation({ uuid: 'a1', parentUuid: 'u1', messageId: 'm1', timestamp: ts(2),
      blocks: [{ type: 'text', text: '答' }] }),
  ])));
  assert.equal(ordinals.get('u1'), 1);
  assert.equal(ordinals.get('a1'), undefined);
});

test('activePathOrdinals: 裁定 turn 的 T 与 groupTurns 同源 —— 提问行，不是 fold 文本行', () => {
  const transcript = readCanonicalTranscript(writeTranscript(dir, askSplitRows()));
  const ordinals = activePathOrdinals(transcript);
  const ask = groupTurns(enumerateLines(transcript)).find(turn => turn.anchorUuid === 'a1');
  assert.equal(ordinals.get('a1'), ask.t);
  assert.equal(ordinals.get('a1'), 3);
});

// ── 生产骨架 + snapshot 指纹 ───────────────────────────────────────────────────

// 物理转录行与对话行不是一回事：meta 行、tool_result 行都占掉 ordinal 却不产出对话行。骨架 fixture
// 故意留着这段空隙 —— T 只有取绝对文件行号才对得上，取 turn 内数组下标一律不对。
const lastUuid = (entries) => (entries.length ? entries[entries.length - 1].uuid : null);
const padTo = (entries, ordinal, tag) => {
  while (entries.length < ordinal) {
    entries.push(userMessage({
      uuid: `${tag}-meta-${entries.length}`, parentUuid: lastUuid(entries),
      text: 'meta', timestamp: ts(0), extra: { isMeta: true },
    }));
  }
  return entries;
};

const turnCwd = '/project';

// 头 U 由 padTo 垫到转录中段：一个承载 turn（含 ABSORB 的打断行）+ 一个真 note-less 的裸命令 turn。
const skeletonEntries = (answer) => {
  const e = padTo([], 12, 'sk');
  e.push(userMessage({ uuid: 'sk-u1', parentUuid: lastUuid(e), text: '第一个问题', timestamp: ts(1) }));
  e.push(assistantObservation({ uuid: 'sk-a1', parentUuid: lastUuid(e), messageId: 'sk-m1', timestamp: ts(2),
    blocks: [{ type: 'text', text: answer }] }));
  e.push(userMessage({ uuid: 'sk-i1', parentUuid: lastUuid(e), text: '[Request interrupted by user]', timestamp: ts(3) }));
  e.push(assistantObservation({ uuid: 'sk-a2', parentUuid: lastUuid(e), messageId: 'sk-m2', timestamp: ts(4),
    blocks: [{ type: 'text', text: '续答' }] }));
  e.push(userMessage({ uuid: 'sk-c1', parentUuid: lastUuid(e), text: '<command-name>/clear</command-name>', timestamp: ts(5) }));
  return e;
};
const linesWithInterrupt = linesOf(skeletonEntries('回答'));
const turns = groupTurns(linesWithInterrupt);
const turnsWithActivity = turns.filter(t => t.hasAssistantActivity);
// 同一批 entries，只把一条 assistant 正文改一个字：槽集合不变，已捕获的 fold 正文变了。
const turnsWithEditedAssistantText = groupTurns(linesOf(skeletonEntries('回荅')));

// 两侧都要超护栏：U 500 字过 U_HEAD_CHARS，A 600 字过 A_CUT_CHARS —— 否则「尾截 A」那半个断言无从落地。
const [turnWithLongU] = groupTurns(linesOf([
  userMessage({ uuid: 'lu-u', text: 'x'.repeat(500), timestamp: ts(1) }),
  assistantObservation({ uuid: 'lu-a', parentUuid: 'lu-u', messageId: 'lu-m', timestamp: ts(2),
    blocks: [{ type: 'text', text: 'y'.repeat(600) }] }),
]));

// 中段密集 CRLF：先截后归一化会把护栏花在马上要塌掉的 \r 上，'z' 一个都留不下来。
const [crlfBudgetTurn] = groupTurns(linesOf([
  userMessage({ uuid: 'cb-u', text: 'a' + '\r\n'.repeat(150) + 'z'.repeat(100), timestamp: ts(1) }),
  assistantObservation({ uuid: 'cb-a', parentUuid: 'cb-u', messageId: 'cb-m', timestamp: ts(2),
    blocks: [{ type: 'text', text: 'ok' }] }),
]));

const multilineEntries = padTo([], 12, 'ml');
multilineEntries.push(userMessage({ uuid: 'ml-u', parentUuid: lastUuid(multilineEntries),
  text: 'u-first\r\nu-second', timestamp: ts(1) }));
padTo(multilineEntries, 18, 'ml');
multilineEntries.push(assistantObservation({ uuid: 'ml-a', parentUuid: lastUuid(multilineEntries),
  messageId: 'ml-m', timestamp: ts(2), blocks: [{ type: 'text', text: 'a-first\ra-second' }] }));
const [multilineSkeletonTurn] = groupTurns(linesOf(multilineEntries));

// U 的第 200 个 UTF-16 码元落在 emoji 高代理上；A 长 601 码元，尾截起点 601-128=473 落在低代理上。
const [astralBoundaryTurn] = groupTurns(linesOf([
  userMessage({ uuid: 'ab-u', text: 'a'.repeat(199) + '😀'.repeat(10), timestamp: ts(1) }),
  assistantObservation({ uuid: 'ab-a', parentUuid: 'ab-u', messageId: 'ab-m', timestamp: ts(2),
    blocks: [{ type: 'text', text: '😀'.repeat(300) + 'z' }] }),
]));

const [turnWithRelativeTool] = groupTurns(linesOf([
  userMessage({ uuid: 'rt-u', text: 'read the store', timestamp: ts(1) }),
  assistantToolUse({ uuid: 'rt-a', parentUuid: 'rt-u', messageId: 'rt-m', toolUseId: 'tok-rt',
    name: 'Read', input: { file_path: 'lib/store.js' }, timestamp: ts(2) }),
  toolResult({ uuid: 'rt-r', parentUuid: 'rt-a', toolUseId: 'tok-rt', content: 'export const x = 1;' }),
]));

// 一条 assistant 消息，头段与尾段可区分：'末条永远取尾' 只有这样才能落地断言。
const [turnWithOneLongAssistant] = groupTurns(linesOf([
  userMessage({ uuid: 'ol-u', text: '问', timestamp: ts(1) }),
  assistantObservation({ uuid: 'ol-a', parentUuid: 'ol-u', messageId: 'ol-m', timestamp: ts(2),
    blocks: [{ type: 'text', text: 'H'.repeat(200) + 'T'.repeat(200) }] }),
]));

// 三条 assistant 消息：首条取头、末条取尾、中段一整条不出现。
const [turnWithThreeAssistants] = groupTurns(linesOf([
  userMessage({ uuid: 'th-u', text: '问', timestamp: ts(1) }),
  assistantObservation({ uuid: 'th-a1', parentUuid: 'th-u', messageId: 'th-m1', timestamp: ts(2),
    blocks: [{ type: 'text', text: 'F'.repeat(200) + 'x'.repeat(200) }] }),
  assistantObservation({ uuid: 'th-a2', parentUuid: 'th-a1', messageId: 'th-m2', timestamp: ts(3),
    blocks: [{ type: 'text', text: 'MIDDLE-MESSAGE' }] }),
  assistantObservation({ uuid: 'th-a3', parentUuid: 'th-a2', messageId: 'th-m3', timestamp: ts(4),
    blocks: [{ type: 'text', text: 'y'.repeat(200) + 'L'.repeat(200) }] }),
]));

// 聚合行：8 条不同路径过 AGG_PATH_CAP，一条重复路径验去重，一条无路径工具只进计数。
const manyToolEntries = [
  userMessage({ uuid: 'mt-u', text: '干活', timestamp: ts(1) }),
  assistantObservation({ uuid: 'mt-a', parentUuid: 'mt-u', messageId: 'mt-m', timestamp: ts(2),
    blocks: [{ type: 'text', text: '开始' }] }),
];
for (const [i, rel] of ['a.js', 'b.js', 'c.js', 'd.js', 'e.js', 'f.js', 'g.js', 'h.js', 'a.js'].entries()) {
  manyToolEntries.push(assistantToolUse({ uuid: `mt-t${i}`, parentUuid: lastUuid(manyToolEntries),
    messageId: `mt-tm${i}`, toolUseId: `tok-mt${i}`, name: 'Read', input: { file_path: `lib/${rel}` },
    timestamp: ts(3 + i) }));
  manyToolEntries.push(toolResult({ uuid: `mt-r${i}`, parentUuid: lastUuid(manyToolEntries),
    toolUseId: `tok-mt${i}`, content: 'ok' }));
}
manyToolEntries.push(assistantToolUse({ uuid: 'mt-np', parentUuid: lastUuid(manyToolEntries),
  messageId: 'mt-npm', toolUseId: 'tok-mt-np', name: 'Bash', input: { command: 'ls' }, timestamp: ts(20) }));
manyToolEntries.push(toolResult({ uuid: 'mt-npr', parentUuid: lastUuid(manyToolEntries),
  toolUseId: 'tok-mt-np', content: 'ok' }));
const [turnWithManyTools] = groupTurns(linesOf(manyToolEntries));

test('骨架：每行带自己的 T，NOTE 槽自带头 U 的 T 作标签，真 note-less 无槽', () => {
  const skeleton = buildSkeleton(turns, 'sess-A', turnCwd);
  assert.match(skeleton, /^CONTEXT EPOCH {2}session sess-A {3}turns \d+$/m);
  assert.match(skeleton, /^CONTEXT EPOCH {2}session sess-A {3}turns \d+\n\nT /);
  assert.match(skeleton, /^T +13 \| U {3}: /m);
  assert.match(skeleton, /^ +\| NOTE\[13\]: ____$/m);
  assert.equal((skeleton.match(/NOTE\[\d+\]: ____/g) || []).length, turnsWithActivity.length);
});

// 聚合行与 NOTE 槽同一个门控。放开聚合行那一半的变异曾在全套 1786 个测试下存活。
test('真 note-less turn 既不出聚合行也不出槽', () => {
  const s = buildSkeleton(groupTurns(clearOnlyLines), 'sess-A', turnCwd);
  assert.ok(!/\| A×/.test(s));
  assert.ok(!/NOTE\[/.test(s));
});

// `/exit` 那块和 `/clear` 那块同形：行都在，聚合行与槽都不在。相邻两个真 turn 的槽必须还在 ——
// 否则「不给槽」就退化成了「整段消失」。
test('骨架：`/exit` 回显块无聚合行无槽，相邻真 turn 的槽照旧', () => {
  const s = buildSkeleton(groupTurns(exitEchoLines), 'sess-A', turnCwd);
  assert.ok(s.includes('Catch you later!'), 'stdout 原文仍要在骨架里');
  assert.ok(s.includes('No response requested.'), '那条 assistant 仍要在骨架里');
  assert.deepEqual(s.match(/NOTE\[\d+\]: ____/g), ['NOTE[1]: ____', 'NOTE[7]: ____']);
  assert.equal((s.match(/\| A×/g) || []).length, 2);
});

// 生产者按块里印的 T 去写 `## NOTE[T]`：头行与槽印不同的行号，这一块就没有一个能用的地址。
test('骨架：裁定 turn 的头行与它的 NOTE 槽印同一个 T —— 提问行', () => {
  const entries = askSplitRows();
  entries.push(assistantObservation({ uuid: 'sk-ask-a', parentUuid: 'ans1', messageId: 'sk-ask-m',
    timestamp: ts(10), blocks: [{ type: 'text', text: '开始执行' }] }));
  const ask = groupTurns(linesOf(entries))[1];
  const s = buildSkeleton([ask], 'sess-A', turnCwd);
  const uRow = s.split('\n').find(row => row.includes('| U   :'));
  assert.equal(Number(uRow.match(/^T\s+(\d+) \|/)[1]), ask.t);
  assert.ok(s.includes(`NOTE[${ask.t}]: ____`));
  assert.equal(ask.t, 3, '提问的 tool_use 行，不是 fold 锚行 2');
});

test('ABSORB 行在骨架里以原文出现（不是清洗后的空串），但不获得 NOTE 槽', () => {
  const s = buildSkeleton(groupTurns(linesWithInterrupt), 'sess-A', turnCwd);
  assert.ok(s.includes('[Request interrupted by user]'));
  assert.equal((s.match(/NOTE\[\d+\]: ____/g) || []).length, 1);   // 只有承载 turn 有槽
});

test('骨架省略：头截 U 尾随裸 …、尾截 A 前置裸 …，无计数；两个护栏各自定尺', () => {
  const s = buildSkeleton([turnWithLongU], 'sess-A', turnCwd);
  assert.ok(!s.includes('[truncated'));
  assert.match(s, /^T +\d+ \| U {3}: x{200}…$/m);   // U 头截：… 收尾
  assert.match(s, /^T +\d+ \| A {3}: …y{128}$/m);   // A 尾截：… 起头
});

test('单条 assistant 消息取尾：末条永远取尾，取头只在 ≥2 条时生效', () => {
  const aRows = buildSkeleton([turnWithOneLongAssistant], 'sess-A', turnCwd)
    .split('\n').filter(r => / \| A {3}: /.test(r));
  assert.equal(aRows.length, 1);
  assert.match(aRows[0], /^T +\d+ \| A {3}: …T{128}$/);   // 取头会以 H 起、以 … 收
});

test('≥2 条：首条取头、末条取尾，中段整条不进骨架', () => {
  const s = buildSkeleton([turnWithThreeAssistants], 'sess-A', turnCwd);
  assert.match(s, /^T +\d+ \| A {3}: F{128}…$/m);
  assert.match(s, /^T +\d+ \| A {3}: …L{128}$/m);
  assert.ok(!s.includes('MIDDLE-MESSAGE'));
  assert.match(s, /^ +\| A×3$/m);                  // 无工具时聚合行只报条数
});

test('聚合行：assistant 条数、工具次数、去重 basename 封顶后记余数；无逐次工具行', () => {
  const s = buildSkeleton([turnWithManyTools], 'sess-A', turnCwd);
  assert.match(s, /^ +\| A×1 · 10 tools: a\.js,b\.js,c\.js,d\.js,e\.js,f\.js \+2$/m);
  assert.ok(!/\| A · : /.test(s));
  assert.ok(!s.includes('/project/lib/'));         // basename only —— 全路径由 search_terms 承担
});

// 两行对调曾在全套下存活,而 `CONTEXT.md` 的 Turn Skeleton 词条与 `NOTES.md` 的示例块都把 NOTE 槽
// 定在块尾 —— producer 是按「块以槽收尾」读的。
test('块尾顺序：聚合行紧接正文，NOTE 槽是块的最后一行', () => {
  const rows = buildSkeleton([turnWithManyTools], 'sess-A', turnCwd).split('\n');
  assert.match(rows[rows.length - 1], /^ +\| NOTE\[\d+\]: ____$/);
  assert.match(rows[rows.length - 2], /^ +\| A×\d+ · \d+ tools/);
});

test('骨架先统一换行符再截断：护栏按归一化后的字符数计，不被 CRLF 吃掉', () => {
  const s = buildSkeleton([crlfBudgetTurn], 'sess-A', turnCwd);
  assert.match(s, /^T +\d+ \| U {3}: z+…$/m);
  assert.ok(!s.includes('\r'));
});

test('骨架多行正文统一换行符，且每个物理行重复自己的 T 与角色', () => {
  const s = buildSkeleton([multilineSkeletonTurn], 'sess-A', turnCwd);
  assert.match(s, /^T +13 \| U {3}: u-first$/m);
  assert.match(s, /^T +13 \| U {3}: u-second$/m);
  assert.match(s, /^T +19 \| A {3}: a-first$/m);
  assert.match(s, /^T +19 \| A {3}: a-second$/m);
  assert.ok(!s.includes('\r'));
});

test('骨架头截/尾截不切断 UTF-16 代理对', () => {
  const s = buildSkeleton([astralBoundaryTurn], 'sess-A', turnCwd);
  for (const ch of s) {
    const cp = ch.codePointAt(0);
    assert.ok(cp < 0xD800 || cp > 0xDFFF, '不得输出孤立代理码元');
  }
});

// ── notes 文件文法 ─────────────────────────────────────────────────────────────
// 分隔符是独占一行的二级标题，正文是标题之间的一切。这才是它比内联 `NOTE[T]: text` 稳的地方：
// 正文里出现 `NOTE[9]:`、`|`、冒号、换行都不影响切段。

test('renderNoteSections：标题由服务端写，槽间一个空行', () => {
  assert.equal(renderNoteSections(['12', '31']), '## NOTE[12]\n\n## NOTE[31]\n');
  assert.equal(renderNoteSections([]), '');
});

test('slotKeysOf：只有带 assistant 活动的 turn 有槽，顺序即 turn 顺序', () => {
  // 三个 turn 两个槽：首问与第二问有 assistant 活动，中间那个裸 /clear 没有。字面量是故意的 ——
  // 拿同一个 filter 反算期望值只会复述实现，槽序被颠倒也看不出来。
  const twoSlots = groupTurns(linesOf([
    userMessage({ uuid: 'sk2-u1', parentUuid: null, text: '第一问', timestamp: ts(1) }),
    assistantObservation({ uuid: 'sk2-a1', parentUuid: 'sk2-u1', messageId: 'sk2-m1', timestamp: ts(2),
      blocks: [{ type: 'text', text: '第一答' }] }),
    userMessage({ uuid: 'sk2-c', parentUuid: 'sk2-a1', text: '<command-name>/clear</command-name>', timestamp: ts(3) }),
    userMessage({ uuid: 'sk2-u2', parentUuid: 'sk2-c', text: '第二问', timestamp: ts(4) }),
    assistantObservation({ uuid: 'sk2-a2', parentUuid: 'sk2-u2', messageId: 'sk2-m2', timestamp: ts(5),
      blocks: [{ type: 'text', text: '第二答' }] }),
  ]));
  assert.deepEqual(slotKeysOf(twoSlots), ['1', '4']);
  assert.deepEqual(slotKeysOf(groupTurns(clearOnlyLines)), []);
  // `/exit` 回显自成一块，它两侧的真 turn 各一个槽 —— 和 `/clear` 一样不占槽。
  assert.deepEqual(slotKeysOf(groupTurns(exitEchoLines)), ['1', '7']);
});

test('parseNoteSections：标题之间的一切都是正文，含换行、冒号、`|` 与内联 NOTE 字样', () => {
  const body = '第一行 · 结论: 砍掉\n第二行 NOTE[9]: 这是正文不是标题\n| 表格行';
  const { sections, issues } = parseNoteSections(`## NOTE[12]\n\n${body}\n\n## NOTE[31]\n\nb\n`, ['12', '31']);
  assert.deepEqual(issues, []);
  assert.deepEqual([...sections], [['12', body], ['31', 'b']]);
});

test('parseNoteSections：严格 `## ` —— 其他标题级不是分隔符，落进上一段正文', () => {
  const { sections } = parseNoteSections('## NOTE[12]\n\nbody\n\n### NOTE[31]\n\nsub\n', ['12', '31']);
  assert.deepEqual([...sections.keys()], ['12']);
  assert.ok(sections.get('12').includes('### NOTE[31]'), '子标题留在正文里，不另开段');
});

// 分隔符是「本次捕获的槽标签」而不是「任何数字标签」。三件事靠这一条同时成立：正文里出现独占一行的
// `## NOTE[N]` 时后半段不会被静默截断；rewind 留下的孤儿标题无法把一条 note 塞给一个没有槽的 turn；
// 每条 issue 的 t 都是真实 turn 序号,而不是文件里恰好写了什么数字。
test('parseNoteSections：非本轮槽的标题不是分隔符 —— 它是正文，后半段不丢', () => {
  const { sections, issues } = parseNoteSections(
    '## NOTE[12]\n\nheading grammar: server prewrites\n## NOTE[31]\nand the producer fills bodies\n', ['12']);
  assert.deepEqual(issues, []);
  assert.deepEqual([...sections.keys()], ['12']);
  assert.ok(sections.get('12').endsWith('and the producer fills bodies'), '截断在标题处就丢了这半句');
  assert.ok(sections.get('12').includes('## NOTE[31]'));
  // 首个槽标题之前也开不出段。只放开这半边的变异曾在全套下存活,而它复活的正是「producer 发明的标题
  // 把一条 note 塞给 note-less turn」。
  assert.deepEqual(
    [...parseNoteSections('## NOTE[999]\n\nINVENTED\n\n## NOTE[12]\n\nreal\n', ['12']).sections],
    [['12', 'real']]);
});

// 无损:同一份字节在槽集合变化时读出不同的段。rewind 掉的槽日后若回来,它的正文原样恢复。
test('parseNoteSections：同一份文本随槽集合改变读法，孤儿段的正文不丢', () => {
  const text = '## NOTE[12]\n\na\n\n## NOTE[31]\n\nb\n';
  assert.equal(parseNoteSections(text, ['12']).sections.get('12'), 'a\n\n## NOTE[31]\n\nb');
  assert.equal(parseNoteSections(text, ['12', '31']).sections.get('31'), 'b');
});

test('parseNoteSections：首标题前的散文被丢弃 —— 它不属于任何槽', () => {
  const { sections, issues } = parseNoteSections('preamble prose\n\n## NOTE[12]\n\nbody\n', ['12']);
  assert.deepEqual(issues, []);
  assert.deepEqual([...sections], [['12', 'body']]);
});

test('parseNoteSections：空正文的段解析为空串，重复标题各报一次 issue', () => {
  const empty = parseNoteSections('## NOTE[12]\n\n## NOTE[31]\n\nb\n', ['12', '31']);
  assert.equal(empty.sections.get('12'), '');
  const dup = parseNoteSections('## NOTE[12]\n\na\n\n## NOTE[12]\n\nb\n', ['12']);
  assert.deepEqual(dup.issues, [{ t: 12, message: 'duplicate NOTE section for this T' }]);
});

// 重复只在真槽上是错误。非槽标签重复不切段 ⇒ 不报 —— 否则它又是一条 producer 删不掉、而且指向一个
// 骨架里根本没有的 T 的拒绝。
test('parseNoteSections：非槽标签重复不报 issue', () => {
  const dup = parseNoteSections('## NOTE[12]\n\na\n\n## NOTE[41]\n\nb\n\n## NOTE[41]\n\nc\n', ['12']);
  assert.deepEqual(dup.issues, []);
  assert.deepEqual([...dup.sections.keys()], ['12']);
});

// 槽键都来自 String(turn.t),所以任何标签长到溢出 Number.MAX_VALUE 都不可能成为分隔符 —— issue 的 t
// 于是永远是安全整数,不会经 Infinity 变成线上的 null。
test('parseNoteSections：溢出 Number 的巨大标签既不切段也不产出 issue', () => {
  const huge = '9'.repeat(309);
  const { sections, issues } = parseNoteSections(
    `## NOTE[0]\n\nbody\n\n## NOTE[${huge}]\n\nx\n\n## NOTE[${huge}]\n\ny\n`, ['0']);
  assert.deepEqual(issues, []);
  assert.deepEqual([...sections.keys()], ['0']);
});

test('parseNoteSections：文件不存在（null）不是崩溃，是零段', () => {
  assert.deepEqual(parseNoteSections(null, ['12']), { sections: new Map(), issues: [] });
});

test('parseNoteSections：标签按数字读 —— `## NOTE[00]` 就是槽 0，不是一个谁都对不上的键', () => {
  assert.deepEqual([...parseNoteSections('## NOTE[00]\n\nbody\n', ['0']).sections], [['0', 'body']]);
  // 归一化后 `## NOTE[0]` 与 `## NOTE[00]` 是同一个槽 ⇒ 报重复（真话），而不是「无此槽」+「缺此槽」两条互相矛盾的假话。
  assert.deepEqual(parseNoteSections('## NOTE[0]\n\na\n\n## NOTE[00]\n\nb\n', ['0']).issues,
    [{ t: 0, message: 'duplicate NOTE section for this T' }]);
});

test('parseNoteSections：标题行尾的空白不吃掉那条 note', () => {
  assert.deepEqual([...parseNoteSections('## NOTE[0]  \n\nbody\n', ['0']).sections], [['0', 'body']]);
});

test('snapshotDigest：槽集合不变但已捕获 fold 正文变化 ⇒ digest 变化', () => {
  assert.notEqual(snapshotDigest(turns, turnCwd), snapshotDigest(turnsWithEditedAssistantText, turnCwd));
});

test('相对工具路径：聚合行只给 basename，search_terms 与 digest 仍共用 turnCwd', () => {
  const skeleton = buildSkeleton([turnWithRelativeTool], 'sess-A', turnCwd);
  const terms = buildSearchTerms({ uText: '', note: null, turn: turnWithRelativeTool, cwd: turnCwd });
  assert.match(skeleton, /^ +\| A×0 · 1 tools: store\.js$/m);
  assert.ok(!skeleton.includes('/project/lib/store.js'));
  assert.ok(terms.split(' ').includes('/project/lib/store.js'));
  assert.notEqual(snapshotDigest([turnWithRelativeTool], '/project'), snapshotDigest([turnWithRelativeTool], '/other'));
});

// ── AskUserQuestion 开 turn ────────────────────────────────────────────────────
// 一次被裁定的答案以 tool_result 落在一行 type:"user" 上，materializeDialogue 把它折进提问那条
// assistant fold。所以下面所有 fixture 都是「纯工具 assistant 行 + 带 toolUseResult 的结果行」。

const askExchange = ({ toolUseId = 'tu1', envelope, toolUseResult, isError, answerTs = ts(9) }) => [
  userMessage({ uuid: 'u1', text: '开始', timestamp: ts(1) }),
  assistantToolUse({ uuid: 'ask1', parentUuid: 'u1', messageId: 'm1', toolUseId,
    name: 'AskUserQuestion', input: { questions: [] }, timestamp: ts(2) }),
  toolResult({ uuid: 'ans1', parentUuid: 'ask1', toolUseId, content: envelope, isError,
    timestamp: answerTs, toolUseResult }),
];
const askTool = (opts) => linesOf(askExchange(opts)).find(l => l.kind === 'tool').tool;
// CC 把同一条 assistant message 的每个 content block 写成独立 JSONL 行：fold 的锚行是首个文本行，
// 提问的 tool_use 行在它之后。
const askSplitRows = () => [
  userMessage({ uuid: 'u1', text: '开始', timestamp: ts(1) }),
  assistantObservation({ uuid: 'a1', parentUuid: 'u1', messageId: 'm1', timestamp: ts(2),
    blocks: [{ type: 'text', text: '先确认一件事' }] }),
  assistantToolUse({ uuid: 'ask1', parentUuid: 'a1', messageId: 'm1', toolUseId: 'tu1',
    name: 'AskUserQuestion', input: { questions: [] }, timestamp: ts(3) }),
  toolResult({ uuid: 'ans1', parentUuid: 'ask1', toolUseId: 'tu1', content: 'envelope',
    timestamp: ts(9), toolUseResult: ONE_Q }),
];

const ONE_Q = {
  questions: [{ question: '开场保留多少铺垫？', header: '开场形态', options: [], multiSelect: false }],
  answers: { '开场保留多少铺垫？': '压缩钩子 1–2 页' },
  annotations: {},
};

test('cleanAskAnswer: 单问投影为 `header → answer`', () => {
  const r = cleanAskAnswer(askTool({ envelope: 'Your questions have been answered: "开场保留多少铺垫？"="压缩钩子 1–2 页". You can now continue with these answers in mind.', toolUseResult: ONE_Q }));
  assert.deepEqual(r, { kind: 'HEAD', cleaned: '开场形态 → 压缩钩子 1–2 页' });
});

test('cleanAskAnswer: 多问按 " — " 连接，保持 answers 的键序', () => {
  const r = cleanAskAnswer(askTool({ envelope: 'envelope', toolUseResult: {
    questions: [
      { question: 'Q1', header: '开场形态' },
      { question: 'Q2', header: 'Demo 形式' },
    ],
    answers: { Q1: 'A1', Q2: 'A2' },
  } }));
  assert.equal(r.cleaned, '开场形态 → A1 — Demo 形式 → A2');
});

test('cleanAskAnswer: 有 notes 时接在答案后 —— 占位符不解析、不剥离', () => {
  const r = cleanAskAnswer(askTool({ envelope: 'envelope', toolUseResult: {
    questions: [{ question: 'Q1', header: '术语对齐' }],
    answers: { Q1: '(notes only)' },
    annotations: { Q1: { notes: 'B不是有效上下文，L-B才是' } },
  } }));
  assert.equal(r.cleaned, '术语对齐 → (notes only) · B不是有效上下文，L-B才是');
});

test('cleanAskAnswer: header 取不到时退回问题原文，不丢这一对', () => {
  const r = cleanAskAnswer(askTool({ envelope: 'envelope', toolUseResult: {
    questions: [], answers: { '这个问题没有对应的 header': '答案' },
  } }));
  assert.equal(r.cleaned, '这个问题没有对应的 header → 答案');
});

test('cleanAskAnswer: isError 一律 ABSORB —— 被 ESC 拒绝与参数校验失败都不是裁定', () => {
  for (const envelope of [
    "The user doesn't want to proceed with this tool use. The tool use was rejected.",
    '<tool_use_error>InputValidationError: AskUserQuestion failed</tool_use_error>',
  ]) {
    assert.deepEqual(cleanAskAnswer(askTool({ envelope, isError: true })),
      { kind: 'ABSORB', cleaned: '' });
  }
});

test('cleanAskAnswer: 结构不可读时降级为原文，不做任何解析', () => {
  const envelope = 'Your questions have been answered: "Q"="A". You can now continue.';
  // toolUseResult 整个缺失
  assert.deepEqual(cleanAskAnswer(askTool({ envelope })), { kind: 'HEAD', cleaned: envelope });
  // answers 变成数组（结构漂移）
  assert.deepEqual(cleanAskAnswer(askTool({ envelope, toolUseResult: { answers: ['A'] } })),
    { kind: 'HEAD', cleaned: envelope });
});

test('cleanAskAnswer: 降级走双端截断 —— 头 200 尾 200，中间一个 …', () => {
  const envelope = 'H'.repeat(300) + 'MIDDLE' + 'T'.repeat(300);
  const r = cleanAskAnswer(askTool({ envelope }));
  assert.equal(r.kind, 'HEAD');
  assert.equal(r.cleaned.length, 401);            // 200 + 1 + 200
  assert.ok(r.cleaned.startsWith('H'.repeat(200)));
  assert.ok(r.cleaned.endsWith('T'.repeat(200)));
  assert.ok(!r.cleaned.includes('MIDDLE'));
  assert.equal(r.cleaned.split('…').length, 2);
});

test('cleanAskAnswer: 可读结构投影为空即 ABSORB，不回退到信封原文', () => {
  const envelope = '这段信封原文不该出现在 u_text 里';
  assert.deepEqual(cleanAskAnswer(askTool({ envelope, toolUseResult: { answers: {} } })),
    { kind: 'ABSORB', cleaned: '' });
});

test('cleanAskAnswer: 别的工具一律 ABSORB', () => {
  const lines = linesOf([
    userMessage({ uuid: 'u1', text: '开始', timestamp: ts(1) }),
    assistantToolUse({ uuid: 'a1', parentUuid: 'u1', messageId: 'm1', toolUseId: 'tu1',
      name: 'Bash', input: { command: 'ls' }, timestamp: ts(2) }),
    toolResult({ uuid: 'r1', parentUuid: 'a1', toolUseId: 'tu1', content: 'out' }),
  ]);
  assert.deepEqual(cleanAskAnswer(lines.find(l => l.kind === 'tool').tool),
    { kind: 'ABSORB', cleaned: '' });
});

test('groupTurns: 裁定答案开出 turn —— T/anchor 取提问行，timestamp 取回答行', () => {
  const lines = linesOf(askExchange({ envelope: 'envelope', toolUseResult: ONE_Q, answerTs: ts(9) }));
  const turns = groupTurns(lines);
  assert.equal(turns.length, 2);                       // '开始' + 裁定
  const ask = turns[1];
  const askLine = lines.find(l => l.kind === 'tool');
  assert.equal(ask.t, askLine.t);
  assert.equal(ask.anchorUuid, 'ask1');                // 提问行的 sourceRef.uuid
  // 回答行的时间戳，epoch ms —— 与可见 U 的 anchorTimestamp 同单位（source_timestamp 是 INTEGER 列）
  assert.equal(ask.anchorTimestamp, Date.parse(ts(9)));
  assert.equal(ask.cleanedU, '开场形态 → 压缩钩子 1–2 页');
  assert.equal(ask.hasAssistantActivity, false);       // head 行不自计 activity
  assert.equal(ask.lines.length, 1);
});

test('groupTurns: 提问行与 fold 文本行不同行时，T 取提问行，anchor 与行的 t 仍是 fold 的', () => {
  const lines = linesOf(askSplitRows());
  const turns = groupTurns(lines);
  assert.equal(turns.length, 2);
  const ask = turns[1];
  const askLine = lines.find(l => l.kind === 'tool');
  assert.equal(askLine.t, 2);                          // fold 锚行：文本行
  assert.equal(askLine.tool.useLineOrdinal, 3);        // 提问的 tool_use 行
  assert.equal(ask.t, 3);
  assert.equal(ask.anchorUuid, 'a1');
  assert.equal(ask.lines[0].t, 2);
});

test('groupTurns: 连问 —— 前一个裁定 turn 无 assistant 活动，仍是独立 turn', () => {
  const lines = linesOf([
    userMessage({ uuid: 'u1', text: '开始', timestamp: ts(1) }),
    assistantToolUse({ uuid: 'ask1', parentUuid: 'u1', messageId: 'm1', toolUseId: 'tu1',
      name: 'AskUserQuestion', input: {}, timestamp: ts(2) }),
    toolResult({ uuid: 'ans1', parentUuid: 'ask1', toolUseId: 'tu1', content: 'e1',
      timestamp: ts(3), toolUseResult: { questions: [{ question: 'Q1', header: 'H1' }], answers: { Q1: 'A1' } } }),
    assistantToolUse({ uuid: 'ask2', parentUuid: 'ans1', messageId: 'm2', toolUseId: 'tu2',
      name: 'AskUserQuestion', input: {}, timestamp: ts(4) }),
    toolResult({ uuid: 'ans2', parentUuid: 'ask2', toolUseId: 'tu2', content: 'e2',
      timestamp: ts(5), toolUseResult: { questions: [{ question: 'Q2', header: 'H2' }], answers: { Q2: 'A2' } } }),
  ]);
  const turns = groupTurns(lines);
  assert.deepEqual(turns.map(t => t.cleanedU), ['开始', 'H1 → A1', 'H2 → A2']);
  assert.equal(turns[1].hasAssistantActivity, false);
  assert.equal(turns[2].hasAssistantActivity, false);
});

test('groupTurns: 被拒绝的提问不开 turn，但仍算前一个 turn 的 assistant 活动', () => {
  const lines = linesOf(askExchange({ envelope: 'rejected', isError: true }));
  const turns = groupTurns(lines);
  assert.equal(turns.length, 1);
  assert.equal(turns[0].cleanedU, '开始');
  assert.equal(turns[0].hasAssistantActivity, true);
  assert.equal(turns[0].lines.length, 2);
});

// 转录停在提问处：tool_use 没有配对结果行 ⇒ 整个 resultMeta 为 null（≠ 结果行存在但没带注解，
// 那种是 raw:undefined 的对象）。实测 live 469 个 AskUserQuestion tool_use 里有 1 个是这个形状。
test('groupTurns: 提问无配对结果行 ⇒ resultMeta 为 null、不开 turn，读取不得抛错', () => {
  const lines = linesOf(askExchange({ envelope: 'envelope', toolUseResult: ONE_Q }).slice(0, -1));
  const askLine = lines.find(l => l.kind === 'tool');
  assert.equal(askLine.tool.resultMeta, null);
  assert.deepEqual(cleanAskAnswer(askLine.tool), { kind: 'ABSORB', cleaned: '' });
  const turns = groupTurns(lines);
  assert.equal(turns.length, 1);
  assert.equal(turns[0].cleanedU, '开始');
  assert.equal(turns[0].hasAssistantActivity, true);   // 提问行仍算前一个 turn 的 assistant 活动
});

test('buildSkeleton: 裁定行只渲染一条 U，不重复渲染成 A · 工具行', () => {
  const lines = linesOf(askExchange({ envelope: 'envelope', toolUseResult: ONE_Q }));
  const turns = groupTurns(lines);
  const skeleton = buildSkeleton(turns, 'sess', '/project');
  const askT = lines.find(l => l.kind === 'tool').t;
  const rows = skeleton.split('\n').filter(r => r.includes(`T ${String(askT).padStart(4)} |`));
  assert.deepEqual(rows, [`T ${String(askT).padStart(4)} | U   : 开场形态 → 压缩钩子 1–2 页`]);
  assert.ok(!skeleton.includes('AskUserQuestion'));
});

// 头位那条工具行已经是本 turn 的 U，再计入聚合行就会让工具次数系统性多一。basename 那一半无从落地：
// 头位只可能是裁定过的 AskUserQuestion，而它解析不出路径。
test('buildSkeleton: 裁定行不进聚合行的工具计数', () => {
  const entries = askExchange({ envelope: 'envelope', toolUseResult: ONE_Q });
  entries.push(assistantObservation({ uuid: 'ah-a', parentUuid: 'ans1', messageId: 'ah-m',
    timestamp: ts(10), blocks: [{ type: 'text', text: '接着做' }] }));
  entries.push(assistantToolUse({ uuid: 'ah-t', parentUuid: 'ah-a', messageId: 'ah-tm',
    toolUseId: 'tok-ah', name: 'Read', input: { file_path: 'lib/store.js' }, timestamp: ts(11) }));
  entries.push(toolResult({ uuid: 'ah-r', parentUuid: 'ah-t', toolUseId: 'tok-ah', content: 'ok' }));
  const s = buildSkeleton(groupTurns(linesOf(entries)), 'sess', '/project');
  assert.match(s, /^ {6}\| A×1 · 1 tools: store\.js$/m);
});

// 实测：调用工具的 turn 里三分之一一条路径都解析不出（纯 Bash），所以这个分支是生产常态。
test('聚合行：零路径解析时只报次数，不留悬空冒号', () => {
  const s = buildSkeleton(groupTurns(linesOf([
    userMessage({ uuid: 'nb-u', text: '跑一下', timestamp: ts(1) }),
    assistantToolUse({ uuid: 'nb-t', parentUuid: 'nb-u', messageId: 'nb-m', toolUseId: 'tok-nb',
      name: 'Bash', input: { command: 'ls' }, timestamp: ts(2) }),
    toolResult({ uuid: 'nb-r', parentUuid: 'nb-t', toolUseId: 'tok-nb', content: 'ok' }),
  ])), 'sess', '/project');
  assert.match(s, /^ {6}\| A×0 · 1 tools$/m);
});

test('聚合行：basename 数恰好等于 AGG_PATH_CAP 时不记余数', () => {
  const e = [userMessage({ uuid: 'cap-u', text: '读六个', timestamp: ts(1) })];
  for (const [i, rel] of ['a.js', 'b.js', 'c.js', 'd.js', 'e.js', 'f.js'].entries()) {
    e.push(assistantToolUse({ uuid: `cap-t${i}`, parentUuid: lastUuid(e), messageId: `cap-m${i}`,
      toolUseId: `tok-cap${i}`, name: 'Read', input: { file_path: `lib/${rel}` }, timestamp: ts(2 + i) }));
    e.push(toolResult({ uuid: `cap-r${i}`, parentUuid: lastUuid(e), toolUseId: `tok-cap${i}`, content: 'ok' }));
  }
  const s = buildSkeleton(groupTurns(linesOf(e)), 'sess', '/project');
  assert.match(s, /^ {6}\| A×0 · 6 tools: a\.js,b\.js,c\.js,d\.js,e\.js,f\.js$/m);
});
